# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a02fd74c990f73adab5a7bd879d91453f22740dcc8a2db877b6eb90b485b55b6a0fecd7c8ecf1a173e6e3a29bbb943e1f35dad437835994c4daa504a0409e8

test:
  secret_key_base: 13a68b2a3a14d9968c8206cec59ff5c37d0add171be036013130fe0477808e968d507e76d0e30347026985308e95d94cbc5acf5a43f95cc6b528a9759ed00869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
